In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

import importlib
import create_population.import_population as pop
import create_population.simulate_errors as sm
import simulation.inclusion_probability as ip

In [2]:
importlib.reload(pop)
importlib.reload(sm)
importlib.reload(ip)

In [3]:
POPULATION_CONFIGS  = {
    "BV_pop": ["BV_5pct_above_SI", "BV_15pct_above_SI", "BV_30pct_above_SI"],
    "f_target": [0.05, 0.20, 0.50],
    "corr_target": [0.10, 0.25, 0.50],
    "r_target": [0.002, 0.01, 0.03, 0.04]
}

# 5% High Values

In [4]:
config = {
            "BV_pop": "BV_5pct_above_SI",
            "f_target": 0.50,
            "corr_target": 0.5,
            "r_target": 0.04,
        }
population_5_HV = pop.import_population(**config)
population_5_HV

                  BV        ER              E
176050  3.800000e+07  0.020668  785397.374077
176051  3.500000e+07  0.020683  723891.990876
176052  2.794469e+06  0.036486  101958.657694
176053  2.771917e+06  0.007433   20604.557719
176054  2.674266e+06  0.074171  198352.507452
...              ...       ...            ...
181075  1.440356e+05  0.000000       0.000000
181076  1.386926e+05  0.235905   32718.247237
181077  1.312505e+05  0.000000       0.000000
181078  1.225623e+05  0.480885   58938.412505
181079  1.207121e+05  0.000000       0.000000

[5030 rows x 3 columns]

In [5]:
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 30)
population_5_HV.rename(columns={"HV": "HV30"}, inplace=True)
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 65)
population_5_HV.rename(columns={"HV": "HV65"}, inplace=True)
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 100)
population_5_HV.rename(columns={"HV": "HV100"}, inplace=True)
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 150)
population_5_HV.rename(columns={"HV": "HV150"}, inplace=True)
population_5_HV

                  BV        ER              E  HV30  HV65  HV100  HV150
176050  3.800000e+07  0.020668  785397.374077     0     0      1      1
176051  3.500000e+07  0.020683  723891.990876     0     0      1      1
176052  2.794469e+06  0.036486  101958.657694     0     0      0      0
176053  2.771917e+06  0.007433   20604.557719     0     0      0      0
176054  2.674266e+06  0.074171  198352.507452     0     0      0      0
...              ...       ...            ...   ...   ...    ...    ...
181075  1.440356e+05  0.000000       0.000000     0     0      0      0
181076  1.386926e+05  0.235905   32718.247237     0     0      0      0
181077  1.312505e+05  0.000000       0.000000     0     0      0      0
181078  1.225623e+05  0.480885   58938.412505     0     0      0      0
181079  1.207121e+05  0.000000       0.000000     0     0      0      0

[5030 rows x 7 columns]

In [6]:
population_5_HV[population_5_HV['HV150']==1].sort_values('BV', ascending=False)

                  BV        ER              E  HV30  HV65  HV100  HV150
176050  3.800000e+07  0.020668  785397.374077     0     0      1      1
177331  3.702584e+07  0.019707  729654.428380     0     0      1      1
178569  3.541684e+07  0.019552  692462.915550     0     0      1      1
176051  3.500000e+07  0.020683  723891.990876     0     0      1      1
180111  3.466395e+07  0.019613  679878.567268     0     0      1      1

# 15% High Values

In [7]:
config = {
            "BV_pop": "BV_15pct_above_SI",
            "f_target": 0.50,
            "corr_target": 0.5,
            "r_target": 0.04,
        }
population_15_HV = pop.import_population(**config)
population_15_HV

                  BV        ER              E
176050  3.800000e+07  0.014520  551762.911639
176051  3.500000e+07  0.013137  459798.364186
176052  2.489339e+06  0.020959   52174.295671
176053  2.469250e+06  0.000000       0.000000
176054  2.382261e+06  0.005333   12705.670525
...              ...       ...            ...
181075  1.283083e+05  0.010843    1391.288369
181076  1.235487e+05  0.000000       0.000000
181077  1.169192e+05  0.776795   90822.208759
181078  1.091797e+05  0.000000       0.000000
181079  1.075315e+05  0.000000       0.000000

[5030 rows x 3 columns]

In [8]:
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 30)
population_15_HV.rename(columns={"HV": "HV30"}, inplace=True)
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 65)
population_15_HV.rename(columns={"HV": "HV65"}, inplace=True)
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 100)
population_15_HV.rename(columns={"HV": "HV100"}, inplace=True)
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 150)
population_15_HV.rename(columns={"HV": "HV150"}, inplace=True)
population_15_HV

                  BV        ER              E  HV30  HV65  HV100  HV150
176050  3.800000e+07  0.014520  551762.911639     0     0      1      1
176051  3.500000e+07  0.013137  459798.364186     0     0      1      1
176052  2.489339e+06  0.020959   52174.295671     0     0      0      0
176053  2.469250e+06  0.000000       0.000000     0     0      0      0
176054  2.382261e+06  0.005333   12705.670525     0     0      0      0
...              ...       ...            ...   ...   ...    ...    ...
181075  1.283083e+05  0.010843    1391.288369     0     0      0      0
181076  1.235487e+05  0.000000       0.000000     0     0      0      0
181077  1.169192e+05  0.776795   90822.208759     0     0      0      0
181078  1.091797e+05  0.000000       0.000000     0     0      0      0
181079  1.075315e+05  0.000000       0.000000     0     0      0      0

[5030 rows x 7 columns]

In [9]:
population_15_HV[population_15_HV['HV150']==1].sort_values('BV', ascending=False)

                  BV        ER              E  HV30  HV65  HV100  HV150
176050  3.800000e+07  0.014520  551762.911639     0     0      1      1
180678  3.760735e+07  0.011471  431396.129792     0     0      1      1
180824  3.735900e+07  0.015250  569728.839711     0     0      1      1
180934  3.733204e+07  0.012262  457777.840504     0     0      1      1
179958  3.703053e+07  0.012741  471790.193997     0     0      1      1
178182  3.657065e+07  0.010598  387571.088062     0     0      1      1
178174  3.566989e+07  0.007418  264586.974897     0     0      1      1
179757  3.563475e+07  0.012701  452585.972933     0     0      1      1
178731  3.545218e+07  0.011043  391483.606860     0     0      1      1
176932  3.519745e+07  0.010708  376883.886321     0     0      1      1
177516  3.507469e+07  0.010780  378092.371695     0     0      1      1
176051  3.500000e+07  0.013137  459798.364186     0     0      1      1
176137  3.489583e+07  0.010744  374928.875666     0     0      1      1
177522  3.478340e+07  0.012729  442774.231414     0     0      1      1
179038  3.441196e+07  0.013400  461108.091213     0     0      1      1

In [14]:
population_15_HV[population_15_HV['HV150']==1].shape[0]

15

# 30% High Values

In [10]:
config = {
            "BV_pop": "BV_30pct_above_SI",
            "f_target": 0.50,
            "corr_target": 0.5,
            "r_target": 0.04,
        }
population_30_HV = pop.import_population(**config)
population_30_HV

                  BV        ER              E
176050  3.800000e+07  0.009914  376718.770812
176051  3.500000e+07  0.008310  290836.259526
176052  2.029332e+06  0.059356  120453.656528
176053  2.012955e+06  0.000000       0.000000
176054  1.942041e+06  0.023155   44968.757841
...              ...       ...            ...
181075  1.045981e+05  0.598338   62585.041949
181076  1.007180e+05  0.000000       0.000000
181077  9.531359e+04  0.000000       0.000000
181078  8.900426e+04  0.016384    1458.275186
181079  8.766063e+04  0.906049   79424.852597

[5030 rows x 3 columns]

In [11]:
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 30)
population_30_HV.rename(columns={"HV": "HV30"}, inplace=True)
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 65)
population_30_HV.rename(columns={"HV": "HV65"}, inplace=True)
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 100)
population_30_HV.rename(columns={"HV": "HV100"}, inplace=True)
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 150)
population_30_HV.rename(columns={"HV": "HV150"}, inplace=True)
population_30_HV

                  BV        ER              E  HV30  HV65  HV100  HV150
176050  3.800000e+07  0.009914  376718.770812     0     0      1      1
176051  3.500000e+07  0.008310  290836.259526     0     0      1      1
176052  2.029332e+06  0.059356  120453.656528     0     0      0      0
176053  2.012955e+06  0.000000       0.000000     0     0      0      0
176054  1.942041e+06  0.023155   44968.757841     0     0      0      0
...              ...       ...            ...   ...   ...    ...    ...
181075  1.045981e+05  0.598338   62585.041949     0     0      0      0
181076  1.007180e+05  0.000000       0.000000     0     0      0      0
181077  9.531359e+04  0.000000       0.000000     0     0      0      0
181078  8.900426e+04  0.016384    1458.275186     0     0      0      0
181079  8.766063e+04  0.906049   79424.852597     0     0      0      0

[5030 rows x 7 columns]

In [12]:
population_30_HV[population_30_HV['HV150']==1].sort_values('BV', ascending=False)

                  BV        ER              E  HV30  HV65  HV100  HV150
176050  3.800000e+07  0.009914  376718.770812     0     0      1      1
176188  3.772422e+07  0.008428  317946.706436     0     0      1      1
179084  3.771020e+07  0.006099  229984.326554     0     0      1      1
179773  3.770445e+07  0.005790  218309.930003     0     0      1      1
178829  3.728658e+07  0.006138  228852.189151     0     0      1      1
180010  3.711302e+07  0.008044  298549.552609     0     0      1      1
176616  3.709178e+07  0.007030  260764.230910     0     0      1      1
176730  3.703485e+07  0.008066  298740.606656     0     0      1      1
180364  3.696130e+07  0.005902  218147.380941     0     0      1      1
176071  3.649720e+07  0.006725  245427.730734     0     0      1      1
178056  3.623023e+07  0.009593  347541.421773     0     0      1      1
180780  3.622083e+07  0.010585  383403.811533     0     0      1      1
178915  3.621795e+07  0.006448  233542.237432     0     0      1      1
180689  3.603758e+07  0.011126  400943.260345     0     0      1      1
179288  3.590166e+07  0.011618  417095.173028     0     0      1      1
176942  3.585186e+07  0.006838  245153.428067     0     0      1      1
180122  3.582299e+07  0.008962  321038.380681     0     0      1      1
178957  3.578195e+07  0.009359  334888.719742     0     0      1      1
179580  3.577861e+07  0.007188  257190.839385     0     0      1      1
177185  3.573865e+07  0.008722  311704.582505     0     0      1      1
179476  3.526248e+07  0.006369  224572.511795     0     0      1      1
179664  3.518861e+07  0.008701  306164.145215     0     0      1      1
179223  3.513915e+07  0.008749  307429.291814     0     0      1      1
180109  3.509975e+07  0.008424  295696.710002     0     0      1      1
176051  3.500000e+07  0.008310  290836.259526     0     0      1      1
179821  3.496866e+07  0.010585  370131.908202     0     0      1      1
179622  3.471651e+07  0.013987  485593.093344     0     0      1      1
180180  3.439617e+07  0.009666  332467.423063     0     0      1      1
176569  3.439136e+07  0.009842  338494.033272     0     0      1      1
176102  3.434869e+07  0.011577  397657.433730     0     0      1      1

In [15]:
population_30_HV[population_30_HV['HV150']==1].shape[0]

30

In [13]:
12/65

0.18461538461538463