In [61]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

import importlib
import create_population.import_population as pop
import create_population.simulate_errors as sm
import simulation.inclusion_probability as ip

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [62]:
importlib.reload(pop)
importlib.reload(sm)
importlib.reload(ip)

In [63]:
POPULATION_CONFIGS  = {
    "BV_pop": ["BV_5pct_above_SI", "BV_15pct_above_SI", "BV_30pct_above_SI"],
    "f_target": [0.05, 0.20, 0.50],
    "corr_target": [0.10, 0.25, 0.50],
    "r_target": [0.002, 0.01, 0.03, 0.04]
}

# 5% High Values

In [82]:
config = {
            "BV_pop": "BV_5pct_above_SI",
            "f_target": 0.50,
            "corr_target": 0.5,
            "r_target": 0.04,
        }
population_5_HV = pop.import_population(**config)
population_5_HV

                  BV        ER             E
176050  6.500000e+07  0.013118  8.526398e+05
176051  1.712990e+07  0.015010  2.571265e+05
176052  9.800000e+07  0.013644  1.337141e+06
176053  8.529361e+05  0.000000  0.000000e+00
176054  8.482547e+05  0.072753  6.171317e+04
...              ...       ...           ...
181075  2.292227e+04  1.000000  2.292227e+04
181076  3.969374e+05  0.000000  0.000000e+00
181077  8.466365e+05  0.048055  4.068520e+04
181078  7.578381e+05  0.114800  8.699969e+04
181079  3.037931e+05  0.286739  8.710941e+04

[5030 rows x 3 columns]

In [83]:
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 30)
population_5_HV.rename(columns={"HV": "HV30"}, inplace=True)
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 65)
population_5_HV.rename(columns={"HV": "HV65"}, inplace=True)
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 100)
population_5_HV.rename(columns={"HV": "HV100"}, inplace=True)
population_5_HV = ip.iterative_hv_selection(population_5_HV, population_5_HV['BV'].sum(), 150)
population_5_HV.rename(columns={"HV": "HV150"}, inplace=True)
population_5_HV

,BV,ER,E,HV30,HV65,HV100,HV150
176050,6.500000e+07,0.013118,8.526398e+05,0.569180,1.000000,1.000000,1.000000
176051,1.712990e+07,0.015010,2.571265e+05,0.150000,0.330736,0.514478,0.776966
176052,9.800000e+07,0.013644,1.337141e+06,0.858149,1.000000,1.000000,1.000000
176053,8.529361e+05,0.000000,0.000000e+00,0.007469,0.016468,0.025617,0.038687
176054,8.482547e+05,0.072753,6.171317e+04,0.007428,0.016378,0.025476,0.038475
...,...,...,...,...,...,...,...
181075,2.292227e+04,1.000000,2.292227e+04,0.000201,0.000443,0.000688,0.001040
181076,3.969374e+05,0.000000,0.000000e+00,0.003476,0.007664,0.011922,0.018004
181077,8.466365e+05,0.048055,4.068520e+04,0.007414,0.016346,0.025428,0.038401
181078,7.578381e+05,0.114800,8.699969e+04,0.006636,0.014632,0.022761,0.034374
181079,3.037931e+05,0.286739,8.710941e+04,0.002660,0.005865,0.009124,0.013779

In [84]:
population_5_HV[population_5_HV['HV150']==1].sort_values('BV', ascending=False)

                BV        ER             E      HV30  HV65  HV100  HV150
176052  98000000.0  0.013644  1.337141e+06  0.858149   1.0    1.0    1.0
176050  65000000.0  0.013118  8.526398e+05  0.569180   1.0    1.0    1.0

# 15% High Values

In [85]:
config = {
            "BV_pop": "BV_15pct_above_SI",
            "f_target": 0.50,
            "corr_target": 0.5,
            "r_target": 0.04,
        }
population_15_HV = pop.import_population(**config)
population_15_HV

                  BV        ER              E
176050  6.500000e+07  0.009028  586845.601346
176051  8.700000e+07  0.008356  727004.133676
176052  9.800000e+07  0.008569  839773.941717
176053  7.651703e+05  0.062656   47942.526566
176054  7.609705e+05  0.000000       0.000000
...              ...       ...            ...
181075  2.056360e+04  0.000000       0.000000
181076  3.560931e+05  0.000000       0.000000
181077  7.595188e+05  0.000000       0.000000
181078  6.798577e+05  0.000000       0.000000
181079  2.725332e+05  0.000000       0.000000

[5030 rows x 3 columns]

In [86]:
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 30)
population_15_HV.rename(columns={"HV": "HV30"}, inplace=True)
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 65)
population_15_HV.rename(columns={"HV": "HV65"}, inplace=True)
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 100)
population_15_HV.rename(columns={"HV": "HV100"}, inplace=True)
population_15_HV = ip.iterative_hv_selection(population_15_HV, population_15_HV['BV'].sum(), 150)
population_15_HV.rename(columns={"HV": "HV150"}, inplace=True)
population_15_HV

,BV,ER,E,HV30,HV65,HV100,HV150
176050,6.500000e+07,0.009028,586845.601346,0.569180,1.000000,1.000000,1.000000
176051,8.700000e+07,0.008356,727004.133676,0.761826,1.000000,1.000000,1.000000
176052,9.800000e+07,0.008569,839773.941717,0.858149,1.000000,1.000000,1.000000
176053,7.651703e+05,0.062656,47942.526566,0.006700,0.015099,0.024196,0.037346
176054,7.609705e+05,0.000000,0.000000,0.006664,0.015016,0.024063,0.037141
...,...,...,...,...,...,...,...
181075,2.056360e+04,0.000000,0.000000,0.000180,0.000406,0.000650,0.001004
181076,3.560931e+05,0.000000,0.000000,0.003118,0.007027,0.011260,0.017380
181077,7.595188e+05,0.000000,0.000000,0.006651,0.014988,0.024018,0.037071
181078,6.798577e+05,0.000000,0.000000,0.005953,0.013416,0.021498,0.033182
181079,2.725332e+05,0.000000,0.000000,0.002386,0.005378,0.008618,0.013302

In [87]:
population_15_HV[population_15_HV['HV150']==1].sort_values('BV', ascending=False)

,BV,ER,E,HV30,HV65,HV100,HV150
176052,9.800000e+07,0.008569,839773.941717,0.858149,1.000000,1.0,1.0
176051,8.700000e+07,0.008356,727004.133676,0.761826,1.000000,1.0,1.0
177332,8.139846e+07,0.009392,764506.064248,0.712775,1.000000,1.0,1.0
176050,6.500000e+07,0.009028,586845.601346,0.569180,1.000000,1.0,1.0
178570,5.397803e+07,0.009982,538815.241094,0.472665,1.000000,1.0,1.0
176070,4.790567e+07,0.007297,349565.809762,0.419492,0.945319,1.0,1.0
180629,4.218612e+07,0.010610,447583.609316,0.369408,0.832456,1.0,1.0
180112,4.114740e+07,0.006790,279378.554034,0.360312,0.811959,1.0,1.0

# 30% High Values

In [88]:
config = {
            "BV_pop": "BV_30pct_above_SI",
            "f_target": 0.50,
            "corr_target": 0.5,
            "r_target": 0.04,
        }
population_30_HV = pop.import_population(**config)
population_30_HV

                  BV        ER              E
176050  6.500000e+07  0.006532  424598.380815
176051  8.700000e+07  0.006295  547676.769127
176052  9.800000e+07  0.006958  681926.129419
176053  6.295940e+05  0.000000       0.000000
176054  6.261383e+05  0.000000       0.000000
...              ...       ...            ...
181075  1.692005e+04  0.000000       0.000000
181076  2.929989e+05  0.000000       0.000000
181077  6.249439e+05  0.000000       0.000000
181078  5.593974e+05  0.000000       0.000000
181079  2.242446e+05  0.000000       0.000000

[5030 rows x 3 columns]

In [89]:
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 30)
population_30_HV.rename(columns={"HV": "HV30"}, inplace=True)
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 65)
population_30_HV.rename(columns={"HV": "HV65"}, inplace=True)
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 100)
population_30_HV.rename(columns={"HV": "HV100"}, inplace=True)
population_30_HV = ip.iterative_hv_selection(population_30_HV, population_30_HV['BV'].sum(), 150)
population_30_HV.rename(columns={"HV": "HV150"}, inplace=True)
population_30_HV

,BV,ER,E,HV30,HV65,HV100,HV150
176050,6.500000e+07,0.006532,424598.380815,0.569180,1.000000,1.000000,1.000000
176051,8.700000e+07,0.006295,547676.769127,0.761826,1.000000,1.000000,1.000000
176052,9.800000e+07,0.006958,681926.129419,0.858149,1.000000,1.000000,1.000000
176053,6.295940e+05,0.000000,0.000000,0.005513,0.013023,0.022138,0.035315
176054,6.261383e+05,0.000000,0.000000,0.005483,0.012952,0.022016,0.035121
...,...,...,...,...,...,...,...
181075,1.692005e+04,0.000000,0.000000,0.000148,0.000350,0.000595,0.000949
181076,2.929989e+05,0.000000,0.000000,0.002566,0.006061,0.010302,0.016435
181077,6.249439e+05,0.000000,0.000000,0.005472,0.012927,0.021974,0.035054
181078,5.593974e+05,0.000000,0.000000,0.004898,0.011571,0.019669,0.031377
181079,2.242446e+05,0.000000,0.000000,0.001964,0.004638,0.007885,0.012578

In [90]:
population_30_HV[population_30_HV['HV150']==1].sort_values('BV', ascending=False)

,BV,ER,E,HV30,HV65,HV100,HV150
176052,9.800000e+07,0.006958,681926.129419,0.858149,1.000000,1.0,1.0
180225,9.130844e+07,0.005321,485894.970727,0.799553,1.000000,1.0,1.0
178580,8.707606e+07,0.006879,598977.371599,0.762492,1.000000,1.0,1.0
176051,8.700000e+07,0.006295,547676.769127,0.761826,1.000000,1.0,1.0
180936,8.661671e+07,0.004772,413349.483283,0.758470,1.000000,1.0,1.0
178110,7.364115e+07,0.006581,484651.508382,0.644848,1.000000,1.0,1.0
176050,6.500000e+07,0.006532,424598.380815,0.569180,1.000000,1.0,1.0
179050,5.829055e+07,0.008522,496771.247171,0.510428,1.000000,1.0,1.0
177828,5.769158e+07,0.007958,459128.315046,0.505183,1.000000,1.0,1.0
178733,5.458026e+07,0.005278,288048.390650,0.477939,1.000000,1.0,1.0
179750,5.428909e+07,0.004575,248392.858216,0.475389,1.000000,1.0,1.0
176933,5.023931e+07,0.007334,368437.601991,0.439927,1.000000,1.0,1.0
177685,4.814719e+07,0.005600,269640.411273,0.421607,0.995923,1.0,1.0
176138,4.509908e+07,0.006027,271789.612027,0.394916,0.932873,1.0,1.0
179206,4.318305e+07,0.005200,224548.960169,0.378138,0.893240,1.0,1.0
179137,3.685308e+07,0.007363,271353.695568,0.322708,0.762305,1.0,1.0

In [91]:
12/65

0.18461538461538463