In [ ]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

import importlib
from config import *
from simulation.run_sim import Simulation
from create_population.import_population import import_population

In [ ]:
for pop_nr in range(1, 29):
    population_config = {
        "pop_file": "synthetic",
        "id": pop_nr
    }
    artificial_pop = import_population(**population_config)

    simulation = Simulation(
        population_ID=population_config["id"],
        population=artificial_pop,
        simulation_config=SIMULATION_SETTINGS,
    )

    simulation.run()
    simulation.export()

Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:05<00:00, 76.08it/s]

Starting sample size 65

100%|██████████| 5000/5000 [01:45<00:00, 47.34it/s]

Starting sample size 100

100%|██████████| 5000/5000 [02:33<00:00, 32.54it/s]

Finished simulation 1
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_1.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:33<00:00, 53.35it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:53<00:00, 28.88it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:20<00:00, 19.17it/s]

Finished simulation 2
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_2.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.06it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:52<00:00, 29.05it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:13<00:00, 19.74it/s]

Finished simulation 3
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_3.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.15it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.09it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.87it/s]

Finished simulation 4
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_4.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 53.98it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:53<00:00, 28.85it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:12<00:00, 19.78it/s]

Finished simulation 5
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_5.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:33<00:00, 53.27it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:52<00:00, 29.05it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:14<00:00, 19.67it/s]

Finished simulation 6
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_6.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:33<00:00, 53.75it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.15it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:12<00:00, 19.81it/s]

Finished simulation 7
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_7.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 53.93it/s]

Starting sample size 65

100%|██████████| 5000/5000 [03:02<00:00, 27.32it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:12<00:00, 19.83it/s]

Finished simulation 8
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_8.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.29it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.07it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:10<00:00, 19.96it/s]

Finished simulation 9
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_9.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.57it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:50<00:00, 29.26it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.85it/s]

Finished simulation 10
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_10.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.88it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:50<00:00, 29.33it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:09<00:00, 20.01it/s]

Finished simulation 11
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_11.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.80it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.20it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.86it/s]

Finished simulation 12
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_12.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.20it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:50<00:00, 29.25it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:14<00:00, 19.66it/s]

Finished simulation 13
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_13.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.14it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.17it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.90it/s]

Finished simulation 14
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_14.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.37it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:53<00:00, 28.89it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:12<00:00, 19.77it/s]

Finished simulation 15
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_15.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:30<00:00, 55.30it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:52<00:00, 28.95it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.90it/s]

Finished simulation 16
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_16.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.35it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.18it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:13<00:00, 19.74it/s]

Finished simulation 17
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_17.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.87it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:53<00:00, 28.88it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:27<00:00, 18.70it/s]

Finished simulation 18
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_18.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.81it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.18it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:10<00:00, 19.97it/s]

Finished simulation 19
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_19.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.44it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.16it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.91it/s]

Finished simulation 20
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_20.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.08it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:53<00:00, 28.79it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.88it/s]

Finished simulation 21
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_21.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.14it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.14it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:13<00:00, 19.75it/s]

Finished simulation 22
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_22.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.71it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:52<00:00, 28.99it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:10<00:00, 19.95it/s]

Finished simulation 23
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_23.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.56it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.18it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:12<00:00, 19.79it/s]

Finished simulation 24
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_24.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:31<00:00, 54.46it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:51<00:00, 29.14it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.90it/s]

Finished simulation 25
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_25.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:32<00:00, 54.21it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:50<00:00, 29.37it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:10<00:00, 19.92it/s]

Finished simulation 26
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_26.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:30<00:00, 55.04it/s]

Starting sample size 65

100%|██████████| 5000/5000 [02:52<00:00, 29.03it/s]

Starting sample size 100

100%|██████████| 5000/5000 [04:11<00:00, 19.86it/s]

Finished simulation 27
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_27.xlsx
Starting configuration 1/1
Starting sample size 30

100%|██████████| 5000/5000 [01:33<00:00, 53.41it/s]

Starting sample size 65

100%|██████████| 5000/5000 [03:09<00:00, 26.38it/s]

Starting sample size 100

100%|██████████| 5000/5000 [06:42<00:00, 12.42it/s]

Finished simulation 28
Exported → C:\Users\isabe\Desktop\PhD\Articles\Sampling_Methods_Comparison\results\resultados_28.xlsx

In [29]:
import pandas as pd
from pathlib import Path

# Folder containing the Excel files
folder = Path("../results")

# Find all Excel files starting with "resultados_"
files = sorted(folder.glob("resultados_*.xlsx"))

# Read and concatenate
df = pd.concat(
    (pd.read_excel(file, sheet_name="métricas") for file in files),
    ignore_index=True
)

print(f"Loaded {len(files)} files.")
print(df.head())

Loaded 28 files.
   sample_size hv_selection       selection_type bound_estimator method  \
0           30    iterative  systematic_sampling              HH    MUS
1           65    iterative  systematic_sampling              HH    MUS
2          100    iterative  systematic_sampling              HH    MUS
3           30    iterative  systematic_sampling              HH    MUS
4           65    iterative  systematic_sampling              HH    MUS

   Population ID  Population Book Value  Population Error Amount  \
0              1           3.425979e+09             4.102917e+07
1              1           3.425979e+09             4.102917e+07
2              1           3.425979e+09             4.102917e+07
3             10           3.425979e+09             3.425979e+07
4             10           3.425979e+09             3.425979e+07

   Population Error Rate  Bias of Error Estimation  \
0               0.011976              70651.648596
1               0.011976             439413.810757
2               0.011976              97174.710819
3               0.010000             108289.238448
4               0.010000              22757.110027

   Precision of Error Estimation  Accuracy of Error Estimation  \
0                   2.033036e+07                  2.033045e+07
1                   1.353521e+07                  1.354027e+07
2                   1.088359e+07                  1.088390e+07
3                   5.338687e+06                  5.339466e+06
4                   3.552676e+06                  3.552727e+06

   Bias of Precision Estimation  Precision of Precision Estimation  \
0                 -80581.126320                       1.063770e+07
1                  91951.240020                       5.252455e+06
2                 -36386.400129                       3.444320e+06
3                 193221.112686                       2.751835e+05
4                  10943.585830                       1.144488e+05

   Accuracy of Precision Estimation  Coverage  Inconclusive   Needed n  \
0                      1.063792e+07    0.5338        0.1880  16.407739
1                      5.253026e+06    0.6704        0.1710  15.757264
2                      3.444456e+06    0.7046        0.1206  15.674062
3                      3.196791e+05    0.8114        0.0000   0.728485
4                      1.148191e+05    0.8002        0.0000   0.698964

   Formula n      Skew
0  18.141782  0.972802
1  18.141782  0.412643
2  18.141782  0.384316
3   0.779321  0.049599
4   0.779321  0.061277

In [30]:
df[df['Population ID']==3]

,sample_size,hv_selection,selection_type,bound_estimator,method,Population ID,Population Book Value,Population Error Amount,Population Error Rate,Bias of Error Estimation,Precision of Error Estimation,Accuracy of Error Estimation,Bias of Precision Estimation,Precision of Precision Estimation,Accuracy of Precision Estimation,Coverage,Inconclusive,Needed n,Formula n,Skew
63,30,iterative,systematic_sampling,HH,MUS,3,3.425979e+09,6.851959e+06,0.002,16243.551821,1.944699e+06,1.944747e+06,39475.254329,254364.490897,256526.937738,0.7708,0.0,0.029834,0.028139,0.097182
64,65,iterative,systematic_sampling,HH,MUS,3,3.425979e+09,6.851959e+06,0.002,-5627.590422,1.290818e+06,1.290826e+06,21744.241464,105640.490041,107215.296712,0.7820,0.0,0.028479,0.028139,0.119630
65,100,iterative,systematic_sampling,HH,MUS,3,3.425979e+09,6.851959e+06,0.002,991.463329,1.016917e+06,1.016918e+06,32896.262317,65382.311619,71007.478785,0.7892,0.0,0.027193,0.028139,0.041913

In [31]:
df.shape[0]

84

In [40]:
df[df['Population Error Amount'] >= df['Population Book Value']*0.02]['Population ID'].unique()

array([14, 15, 16, 17, 18, 19, 20, 21, 22])

In [47]:
populations_above_mat = [14, 15, 16, 17, 18, 19, 20, 21, 22, 1]
df_filtered = df[~df['Population ID'].isin(populations_above_mat)]
df_filtered.head()

,sample_size,hv_selection,selection_type,bound_estimator,method,Population ID,Population Book Value,Population Error Amount,Population Error Rate,Bias of Error Estimation,Precision of Error Estimation,Accuracy of Error Estimation,Bias of Precision Estimation,Precision of Precision Estimation,Accuracy of Precision Estimation,Coverage,Inconclusive,Needed n,Formula n,Skew
3,30,iterative,systematic_sampling,HH,MUS,10,3.425979e+09,3.425979e+07,0.01,108289.238448,5.338687e+06,5.339466e+06,193221.112686,2.751835e+05,3.196791e+05,0.8114,0.0000,0.728485,0.779321,0.049599
4,65,iterative,systematic_sampling,HH,MUS,10,3.425979e+09,3.425979e+07,0.01,22757.110027,3.552676e+06,3.552727e+06,10943.585830,1.144488e+05,1.148191e+05,0.8002,0.0000,0.698964,0.779321,0.061277
5,100,iterative,systematic_sampling,HH,MUS,10,3.425979e+09,3.425979e+07,0.01,56875.820968,2.854778e+06,2.855180e+06,-7500.411039,7.170462e+04,7.198220e+04,0.8048,0.0000,0.694345,0.779321,-0.007610
6,30,iterative,systematic_sampling,HH,MUS,11,3.425979e+09,3.425979e+07,0.01,-105646.304249,1.917138e+07,1.917158e+07,89560.601670,6.810866e+06,6.811283e+06,0.7042,0.2024,9.394169,6.983753,0.261008
7,65,iterative,systematic_sampling,HH,MUS,11,3.425979e+09,3.425979e+07,0.01,204195.365394,1.260786e+07,1.260903e+07,305611.664027,2.642699e+06,2.655197e+06,0.7472,0.1010,8.802911,6.983753,0.254513

In [49]:
group_cols = ["method", "sample_size", "hv_selection", "selection_type", "bound_estimator"]
excluded_cols = group_cols
value_cols = df_filtered.columns.difference(excluded_cols)
summary = (
        df_filtered
        .groupby(group_cols)["Coverage"]
        .describe()
        .T
    )

In [50]:
summary

method                          MUS
sample_size                     30                  65                  100
hv_selection              iterative           iterative           iterative
selection_type  systematic_sampling systematic_sampling systematic_sampling
bound_estimator                  HH                  HH                  HH
count                     18.000000            18.00000           18.000000
mean                       0.759722             0.77690            0.784600
std                        0.041382             0.02292            0.019819
min                        0.699400             0.74520            0.749000
25%                        0.713350             0.74885            0.766100
50%                        0.770700             0.78320            0.790700
75%                        0.799750             0.79855            0.801150
max                        0.811400             0.80340            0.809800